# Reusable workflow to run code quality checks
# Sets up Python and runs composite checks (ruff, pre-commit, pip-audit)
# Supports manual dispatch and workflow_call triggers
name: Code Quality Checker
on:
  #  push:
  #    branches-ignore:
  #      - main
  #      - master
  #      - development
  #
  #  pull_request:
  #    branches-ignore:
  #      - main
  #      - master
  #      - development
  workflow_dispatch:
  workflow_call:


jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python-dependencies
        with:
          python-version: '3.13'

      - name: Run Code Quality Checks
        uses: ./.github/actions/code-quality-checks
        with:
          python-version: '3.13'
          run-pre-commit: 'true'
          run-pip-audit: 'true'
